### ISSUE TITLE
Which epoch is the pretrain in *_test.yaml

### ISSUE THREAD

**Issue by laohuijiadezhu** [ttlmh/Bridge-Prompt#10]
Hello, thank you very much for your detailed sharing. I have the following questions:

1. Which epoch is the “pretrain" key in gtea_test.yaml and salads_test.yml? As you give in breakfast_test.yml, pretrain: "./exp/clip_ucf/ViT-B/16/breakfast/20211114_052417_splt1_adj/14_epoch.pt", you explicitly mentioned 14 epoch.
2. Why are there * and *_wc in ordinal action recognition? What does WC mean？And what are your considerations in this?

Looking forward to your reply!

**Comment by ttlmh** [comment]
Hi, thanks for your interest in our work!

1. The value of the key `pretrain` should be the directory of the pre-trained model you have trained before. The existing value is the pre-trained model we used during our experiment, which was also the last epoch (14th) we trained on Breakfast dataset.
2. `wc` refers to '**w**ithout **c**ount information'. Since our approach can predict the count of ordinal actions inside a window, we can choose to prune the predicted actions using the predicted count information. * refers to the final results considering the count information, while *_wc is the opposite.

**Comment by laohuijiadezhu** [comment]
Thank you for your reply! Your answer has solved most of my doubts. But I still have few questions:

1. Write this sentence in your paper: ”The model is trained for 50 epochs on GTEA and 50Salads, and 35 epochs on Breakfast.“. For breakfast, I think 35th epoch is the last. Why do you say the 14th epoch is the last？Is it true that the 14th one performed well in the verification? If the answer is yes, I want to know which epoch performs well on the other two datasets. Due to resource constraints, I can't run each epoch of each dataset myself, and then choose the best one. I want to know explicitly which epoch is the best.
2. What does “prune the predicted actions” mean? In particular, what does “prune” mean? I don't know how to prune by the predicted number of actions. Can you give an example?

Look forward to your reply again！

**Comment by ttlmh** [comment]
1. Sorry for the mistake, the final training epoch for Breakfast is not the 14th, the value of key `pretrain` in `breakfast_test.yaml` is not the final version. You can directly take the last epoch for further uses, or, if conditions allow, choose one with the best ordinal action prediction scores.
2. During the inference process, since we are unable to know in advance how many actions are there in each window, we simply find the best match action for all the ordinal prompts. At the same time, we also predict the count information using the statistical prompt. Thus, we can remove the redundant predictions. For example, the original predictions can be:
`Firstly, the action is taking bread. Secondly, the action is putting cheese on bread.`
However, the count prediction is:
`This video clip has one action.`
In this case, the second prediction will be discarded (pruned).

**Comment by laohuijiadezhu** [comment]
I am grateful to you for meticulous answers to my questions. Thank you very much!
